# -*- coding: utf-8 -*-
"""Assignment_list_comprehensation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qEV40W_j0vWvGvgXJfUpcBXGdiP0GwOe
"""

house_area_price_dict = {1056 : 39, 2600 : 120 , 1520 : 95, 1200 : 50, 2700 : 200, 1100 : 40}
house_areas = [k for k,v in house_area_price_dict.items()]
house_price = [v for k,v in house_area_price_dict.items()]
print(house_areas)
print(house_price)

predicted_house_prices = [0.05*area+10 for area in house_areas]
print(predicted_house_prices)

list1 = []
list1.append(predicted_house_prices)
list1

list1.append(house_price)
list1

for i in list1:
  for j in i:
    print((j^2)-)





""" Problem 3.  
You are given a sentence : "I have been walking and running and dancing and smiling and laughing all my life, yet it all seems pointless."
You are required to extract all those words from this sentence in a list which ends with ing
"""

# Your sentence
my_sentence = "I have been walking and running and dancing and smiling and laughing all my life, yet it all seems pointless."

# Using list comprehension, extract those words which ends with ing
m=[]
l = my_sentence.split()
for i in l:
 m.append(i)
 if i == l[len(l)-1]:

#all_words_in_sentence 
   print(m)
  
# Words ending with ing
f = []
for j in m:
  z = j.endswith('ing')
  if z == True:
    f.append(j)
    if j== 'laughing':
      print(f)
    else: pass
  else:
    pass

"""Problem 4   
Natural Language Processing or NLP is one of the most promising fields in Machine Learning. Most of the times in NLP we deal with the textual data (a bunch of strings). Sometimes when we are processing the text, it is a common practice to get rid of some set of stop words from our original text. By default stop words are very common words used in English language such as and, or, punctuations etc.
In this exercise, you are provided with a default set of stop words and you need to add some extra set of custom words and remove these words from the given sentence and obtain the sentence without the stop words
"""

# A sample sentence 

sentence = 'Hello, good morning folks! Today we will announce the half yearly performance results of the company. Due to the ongoing COVID-19 pandemic, our profits have declined by 60% as compared to the last year'

# Print your sentence
print(sentence)


# Default set of stop words 
stop_words = {"i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself", 
              "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself",
              "they", "them", "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that",
              "these", "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had",
              "having", "do", "does", "did", "doing", "a", "an", "the", "and", "but", "if", "or", "because",
              "as", "until", "while", "of", "at", "by", "for", "with", "about", "against", "between", "into",
              "through", "during", "before", "after", "above", "below", "to", "from", "up", "down", "in", "out", 
              "on", "off", "over", "under", "again", "further", "then", "once", "here", "there", "when", "where",
              "why", "how", "all", "any", "both", "each", "few", "more", "most", "other", "some", "such", "no",
              "nor", "not", "only", "own", "same", "so", "than", "too", "very", "s", "t", "can", "will", "just",
              "don", "should", "now"}


# Update the set of stop words by adding the custom stop words
custom_stop_words = ["hello","good","morning","half","year"]
stop_words.update(custom_stop_words)
print(stop_words)

# Print the stop words in a sorted manner
y = sorted(stop_words)
print(y)

# Create the list of words in the given sentence
b = sentence.split()
print(b)


# Use list comprehension to remove the set of updated stop words from the list of words
list1 = [x for x in b if x not in y]
#for x in b:
  #if x not in y:
print('-----------------------------------------------------------------------------------')
print(list1)


# Finally using the join() method, get the sentence without the stop words. Keep in mind that every word in the sentence will be separated by space
sentence = ' '.join(list1)

print('-------------------------------------------------------------------------------------------------')
# Print the modified sentence
print(sentence)